language: php
notifications:
 email:
  - sdksupport@vantiv.com
env:
 global:
  - BUILD_DIR=`pwd`
  - PAYFAC_MP_CONFIG_DIR=$BUILD_DIR/src
  - PAYFAC_MP_CONFIG_FILE=$PAYFAC_MP_CONFIG_DIR/MP_SDK_config.ini
install:
 - composer install
script:
 - echo $BUILD_DIR
 - echo $PAYFAC_MP_CONFIG_FILE
 - echo 'username=USERNAME'>$PAYFAC_MP_CONFIG_FILE
 - echo 'password=PASSWORD'>>$PAYFAC_MP_CONFIG_FILE
 - echo "currency_merchant_map ['DEFAULT']=1288791">>$PAYFAC_MP_CONFIG_FILE
 - echo 'url=https://www.testvantivcnp.com/sandbox/payfac/'>>$PAYFAC_MP_CONFIG_FILE
 - echo 'proxy='>>$PAYFAC_MP_CONFIG_FILE
 - echo 'timeout=50000'>>$PAYFAC_MP_CONFIG_FILE
 - echo 'printXml=true'>>$PAYFAC_MP_CONFIG_FILE
 - echo 'neuterXml=0'>>$PAYFAC_MP_CONFIG_FILE
 - cat $PAYFAC_MP_CONFIG_FILE
 - $BUILD_DIR/vendor/bin/phpunit --log-junit $BUILD_DIR/reports/tests.xml --coverage-clover=coverage.xml

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 skip_cleanup: true
 on:
  tags: true

after_success:
 - bash <(curl -s https://codecov.io/bash)
